/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RescueGalleryRouteImport } from './routes/rescue-gallery'
import { Route as MissionAdventureIdRouteImport } from './routes/mission.$adventureId'
import { Route as PracticeSkillIdRouteImport } from './routes/practice.$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueGalleryRoute = RescueGalleryRouteImport.update({
  id: '/rescue-gallery',
  path: '/rescue-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionAdventureIdRoute = MissionAdventureIdRouteImport.update({
  id: '/mission/$adventureId',
  path: '/mission/$adventureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSkillIdRoute = PracticeSkillIdRouteImport.update({
  id: '/practice/$skillId',
  path: '/practice/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/parent': typeof ParentRoute
  '/shop': typeof ShopRoute
  '/skills': typeof SkillsRoute
  '/rescue-gallery': typeof RescueGalleryRoute
  '/mission/$adventureId': typeof MissionAdventureIdRoute
  '/practice/$skillId': typeof PracticeSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/parent': typeof ParentRoute
  '/shop': typeof ShopRoute
  '/skills': typeof SkillsRoute
  '/rescue-gallery': typeof RescueGalleryRoute
  '/mission/$adventureId': typeof MissionAdventureIdRoute
  '/practice/$skillId': typeof PracticeSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/parent': typeof ParentRoute
  '/shop': typeof ShopRoute
  '/skills': typeof SkillsRoute
  '/rescue-gallery': typeof RescueGalleryRoute
  '/mission/$adventureId': typeof MissionAdventureIdRoute
  '/practice/$skillId': typeof PracticeSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/parent'
    | '/shop'
    | '/skills'
    | '/rescue-gallery'
    | '/mission/$adventureId'
    | '/practice/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/parent'
    | '/shop'
    | '/skills'
    | '/rescue-gallery'
    | '/mission/$adventureId'
    | '/practice/$skillId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/parent'
    | '/shop'
    | '/skills'
    | '/rescue-gallery'
    | '/mission/$adventureId'
    | '/practice/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ParentRoute: typeof ParentRoute
  ShopRoute: typeof ShopRoute
  SkillsRoute: typeof SkillsRoute
  RescueGalleryRoute: typeof RescueGalleryRoute
  MissionAdventureIdRoute: typeof MissionAdventureIdRoute
  PracticeSkillIdRoute: typeof PracticeSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue-gallery': {
      id: '/rescue-gallery'
      path: '/rescue-gallery'
      fullPath: '/rescue-gallery'
      preLoaderRoute: typeof RescueGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission/$adventureId': {
      id: '/mission/$adventureId'
      path: '/mission/$adventureId'
      fullPath: '/mission/$adventureId'
      preLoaderRoute: typeof MissionAdventureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$skillId': {
      id: '/practice/$skillId'
      path: '/practice/$skillId'
      fullPath: '/practice/$skillId'
      preLoaderRoute: typeof PracticeSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ParentRoute: ParentRoute,
  ShopRoute: ShopRoute,
  SkillsRoute: SkillsRoute,
  RescueGalleryRoute: RescueGalleryRoute,
  MissionAdventureIdRoute: MissionAdventureIdRoute,
  PracticeSkillIdRoute: PracticeSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
